### ISSUE TITLE
info boxes

### ISSUE THREAD

**Issue by ceyonur** [ava-labs/avalanche-docs-beta#11]
We had "nice" looking references in gitbook but seems docusaraus (or simply 🦖 ) puts them into info boxes. 

📖 
![resim](https://user-images.githubusercontent.com/18367708/141373068-66158d9c-8303-4cfc-af98-9284e7093761.png)

🦖 
![resim](https://user-images.githubusercontent.com/18367708/141373111-45b1e671-6b59-4907-9813-f0c9993c1163.png)

**Comment by yulin-dong** [comment]
Gitbook has this page-ref plug-in and no counter-part in Docusaurus found yet.
