### ISSUE TITLE
left pane improvements

### ISSUE THREAD

**Issue by ceyonur** [ava-labs/avalanche-docs-beta#12]
We can try to either reduce the font size in left pane or change the font altogether. Currently font seems a little bit thick and also spacing between each element seems too much.

It might also be good to show different colors (like pale/faded) for different levels of titles.

![resim](https://user-images.githubusercontent.com/18367708/141373726-1a73c615-f8a0-4df3-81af-2610f93f735d.png)

**Comment by yulin-dong** [comment]
The font-size on the old site is 14px, while it is 16px on the new one.

**Comment by yulin-dong** [comment]
See https://github.com/ava-labs/avalanche-docs-beta/pull/13
